////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// Unity File                                                                 //
//                                                                            //
// Generated by Unity Build.                                                  //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include "DCRenderHeader.h"

#pragma message("RenderUnity/Unity_Utility.cpp(11) : [1 / 4] ./DCRenderUtils.cpp")
#include ".\DCRenderUtils.cpp"

#pragma message("RenderUnity/Unity_Utility.cpp(14) : [2 / 4] ./DCTranslator.cpp")
#include ".\DCTranslator.cpp"

#pragma message("RenderUnity/Unity_Utility.cpp(17) : [3 / 4] ./QuadGeometry.cpp")
#include ".\QuadGeometry.cpp"

#pragma message("RenderUnity/Unity_Utility.cpp(20) : [4 / 4] ./ShaderLoader.cpp")
#include ".\ShaderLoader.cpp"

