////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// Unity File                                                                 //
//                                                                            //
// Generated by Unity Build.                                                  //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include "DCRenderHeader.h"

#pragma message("RenderUnity/Unity_RenderCore.cpp(11) : [1 / 4] ./DCRenderer.cpp")
#include ".\DCRenderer.cpp"

#pragma message("RenderUnity/Unity_RenderCore.cpp(14) : [2 / 4] ./DCRenderSetter.cpp")
#include ".\DCRenderSetter.cpp"

#pragma message("RenderUnity/Unity_RenderCore.cpp(17) : [3 / 4] ./DCRenderState.cpp")
#include ".\DCRenderState.cpp"

#pragma message("RenderUnity/Unity_RenderCore.cpp(20) : [4 / 4] ./DCRenderType.cpp")
#include ".\DCRenderType.cpp"

