////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// Unity File                                                                 //
//                                                                            //
// Generated by Unity Build.                                                  //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#pragma message("Unities/RenderUnity.cpp(9) : [1 / 23] ./Src/Render/DCRenderHeader.cpp")
#include ".\Src\Render\DCRenderHeader.cpp"

#pragma message("Unities/RenderUnity.cpp(12) : [2 / 23] ./Src/Render/DCSurface.cpp")
#include ".\Src\Render\DCSurface.cpp"

#pragma message("Unities/RenderUnity.cpp(15) : [3 / 23] ./Src/Render/DCTexture.cpp")
#include ".\Src\Render\DCTexture.cpp"

#pragma message("Unities/RenderUnity.cpp(18) : [4 / 23] ./Src/Render/DCUtils.cpp")
#include ".\Src\Render\DCUtils.cpp"

#pragma message("Unities/RenderUnity.cpp(21) : [5 / 23] ./Src/Render/DCGeometry.cpp")
#include ".\Src\Render\DCGeometry.cpp"

#pragma message("Unities/RenderUnity.cpp(24) : [6 / 23] ./Src/Render/DCMapTile.cpp")
#include ".\Src\Render\DCMapTile.cpp"

#pragma message("Unities/RenderUnity.cpp(27) : [7 / 23] ./Src/Render/DCMaterial.cpp")
#include ".\Src\Render\DCMaterial.cpp"

#pragma message("Unities/RenderUnity.cpp(30) : [8 / 23] ./Src/Render/DCModel.cpp")
#include ".\Src\Render\DCModel.cpp"

#pragma message("Unities/RenderUnity.cpp(33) : [9 / 23] ./Src/Render/DCModelInstance.cpp")
#include ".\Src\Render\DCModelInstance.cpp"

#pragma message("Unities/RenderUnity.cpp(36) : [10 / 23] ./Src/Render/DCSubModel.cpp")
#include ".\Src\Render\DCSubModel.cpp"

#pragma message("Unities/RenderUnity.cpp(39) : [11 / 23] ./Src/Render/DCWMO.cpp")
#include ".\Src\Render\DCWMO.cpp"

#pragma message("Unities/RenderUnity.cpp(42) : [12 / 23] ./Src/Render/Terrain.cpp")
#include ".\Src\Render\Terrain.cpp"

#pragma message("Unities/RenderUnity.cpp(45) : [13 / 23] ./Src/Render/DCRenderer.cpp")
#include ".\Src\Render\DCRenderer.cpp"

#pragma message("Unities/RenderUnity.cpp(48) : [14 / 23] ./Src/Render/DCRenderSetter.cpp")
#include ".\Src\Render\DCRenderSetter.cpp"

#pragma message("Unities/RenderUnity.cpp(51) : [15 / 23] ./Src/Render/DCRenderState.cpp")
#include ".\Src\Render\DCRenderState.cpp"

#pragma message("Unities/RenderUnity.cpp(54) : [16 / 23] ./Src/Render/DCRenderType.cpp")
#include ".\Src\Render\DCRenderType.cpp"

#pragma message("Unities/RenderUnity.cpp(57) : [17 / 23] ./Src/Render/PostFXRenderer.cpp")
#include ".\Src\Render\PostFXRenderer.cpp"

#pragma message("Unities/RenderUnity.cpp(60) : [18 / 23] ./Src/Render/DCShaderManager.cpp")
#include ".\Src\Render\DCShaderManager.cpp"

#pragma message("Unities/RenderUnity.cpp(63) : [19 / 23] ./Src/Render/DCRenderUtils.cpp")
#include ".\Src\Render\DCRenderUtils.cpp"

#pragma message("Unities/RenderUnity.cpp(66) : [20 / 23] ./Src/Render/DCTranslator.cpp")
#include ".\Src\Render\DCTranslator.cpp"

#pragma message("Unities/RenderUnity.cpp(69) : [21 / 23] ./Src/Render/QuadGeometry.cpp")
#include ".\Src\Render\QuadGeometry.cpp"

#pragma message("Unities/RenderUnity.cpp(75) : [23 / 23] ./Src/Render/VertexDeclarationManager.cpp")
#include ".\Src\Render\VertexDeclarationManager.cpp"

