////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// Unity File                                                                 //
//                                                                            //
// Generated by Unity Build.                                                  //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#pragma message("Unities/RenderUnity.cpp(9) : [1 / 31] ./Src/Render/DCRenderHeader.cpp")
#include ".\Src\Render\DCRenderHeader.cpp"

#pragma message("Unities/RenderUnity.cpp(12) : [2 / 31] ./Src/Render/DCSurface.cpp")
#include ".\Src\Render\DCSurface.cpp"

#pragma message("Unities/RenderUnity.cpp(15) : [3 / 31] ./Src/Render/DCTexture.cpp")
#include ".\Src\Render\DCTexture.cpp"

#pragma message("Unities/RenderUnity.cpp(18) : [4 / 31] ./Src/Render/DCUtils.cpp")
#include ".\Src\Render\DCUtils.cpp"

#pragma message("Unities/RenderUnity.cpp(21) : [5 / 31] ./Src/Render/DXUT/dxstdafx.cpp")
#include ".\Src\Render\DXUT\dxstdafx.cpp"

#pragma message("Unities/RenderUnity.cpp(24) : [6 / 31] ./Src/Render/DXUT/DXUT.cpp")
#include ".\Src\Render\DXUT\DXUT.cpp"

#pragma message("Unities/RenderUnity.cpp(27) : [7 / 31] ./Src/Render/DXUT/DXUTenum.cpp")
#include ".\Src\Render\DXUT\DXUTenum.cpp"

#pragma message("Unities/RenderUnity.cpp(30) : [8 / 31] ./Src/Render/DXUT/DXUTgui.cpp")
#include ".\Src\Render\DXUT\DXUTgui.cpp"

#pragma message("Unities/RenderUnity.cpp(33) : [9 / 31] ./Src/Render/DXUT/DXUTMesh.cpp")
#include ".\Src\Render\DXUT\DXUTMesh.cpp"

#pragma message("Unities/RenderUnity.cpp(36) : [10 / 31] ./Src/Render/DXUT/DXUTmisc.cpp")
#include ".\Src\Render\DXUT\DXUTmisc.cpp"

#pragma message("Unities/RenderUnity.cpp(39) : [11 / 31] ./Src/Render/DXUT/DXUTRes.cpp")
#include ".\Src\Render\DXUT\DXUTRes.cpp"

#pragma message("Unities/RenderUnity.cpp(42) : [12 / 31] ./Src/Render/DXUT/DXUTSettingsDlg.cpp")
#include ".\Src\Render\DXUT\DXUTSettingsDlg.cpp"

#pragma message("Unities/RenderUnity.cpp(45) : [13 / 31] ./Src/Render/DCGeometry.cpp")
#include ".\Src\Render\DCGeometry.cpp"

#pragma message("Unities/RenderUnity.cpp(48) : [14 / 31] ./Src/Render/DCMapTile.cpp")
#include ".\Src\Render\DCMapTile.cpp"

#pragma message("Unities/RenderUnity.cpp(51) : [15 / 31] ./Src/Render/DCMaterial.cpp")
#include ".\Src\Render\DCMaterial.cpp"

#pragma message("Unities/RenderUnity.cpp(54) : [16 / 31] ./Src/Render/DCModel.cpp")
#include ".\Src\Render\DCModel.cpp"

#pragma message("Unities/RenderUnity.cpp(57) : [17 / 31] ./Src/Render/DCModelInstance.cpp")
#include ".\Src\Render\DCModelInstance.cpp"

#pragma message("Unities/RenderUnity.cpp(60) : [18 / 31] ./Src/Render/DCSubModel.cpp")
#include ".\Src\Render\DCSubModel.cpp"

#pragma message("Unities/RenderUnity.cpp(63) : [19 / 31] ./Src/Render/DCWMO.cpp")
#include ".\Src\Render\DCWMO.cpp"

#pragma message("Unities/RenderUnity.cpp(66) : [20 / 31] ./Src/Render/Terrain.cpp")
#include ".\Src\Render\Terrain.cpp"

#pragma message("Unities/RenderUnity.cpp(69) : [21 / 31] ./Src/Render/DCRenderer.cpp")
#include ".\Src\Render\DCRenderer.cpp"

#pragma message("Unities/RenderUnity.cpp(72) : [22 / 31] ./Src/Render/DCRenderSetter.cpp")
#include ".\Src\Render\DCRenderSetter.cpp"

#pragma message("Unities/RenderUnity.cpp(75) : [23 / 31] ./Src/Render/DCRenderState.cpp")
#include ".\Src\Render\DCRenderState.cpp"

#pragma message("Unities/RenderUnity.cpp(78) : [24 / 31] ./Src/Render/DCRenderType.cpp")
#include ".\Src\Render\DCRenderType.cpp"

#pragma message("Unities/RenderUnity.cpp(81) : [25 / 31] ./Src/Render/PostFXRenderer.cpp")
#include ".\Src\Render\PostFXRenderer.cpp"

#pragma message("Unities/RenderUnity.cpp(84) : [26 / 31] ./Src/Render/DCShaderManager.cpp")
#include ".\Src\Render\DCShaderManager.cpp"

#pragma message("Unities/RenderUnity.cpp(87) : [27 / 31] ./Src/Render/DCRenderUtils.cpp")
#include ".\Src\Render\DCRenderUtils.cpp"

#pragma message("Unities/RenderUnity.cpp(90) : [28 / 31] ./Src/Render/DCTranslator.cpp")
#include ".\Src\Render\DCTranslator.cpp"

#pragma message("Unities/RenderUnity.cpp(93) : [29 / 31] ./Src/Render/QuadGeometry.cpp")
#include ".\Src\Render\QuadGeometry.cpp"

#pragma message("Unities/RenderUnity.cpp(96) : [30 / 31] ./Src/Render/ShaderLoader.cpp")
#include ".\Src\Render\ShaderLoader.cpp"

#pragma message("Unities/RenderUnity.cpp(99) : [31 / 31] ./Src/Render/VertexDeclarationManager.cpp")
#include ".\Src\Render\VertexDeclarationManager.cpp"

