////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// Unity File                                                                 //
//                                                                            //
// Generated by Unity Build.                                                  //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include "DCRenderHeader.h"

#pragma message("Render_Unity/Unity_Shader.cpp(11) : [1 / 4] ./DCBoneShader.cpp")
#include ".\DCBoneShader.cpp"

#pragma message("Render_Unity/Unity_Shader.cpp(14) : [2 / 4] ./DCCreatureShader.cpp")
#include ".\DCCreatureShader.cpp"

#pragma message("Render_Unity/Unity_Shader.cpp(17) : [3 / 4] ./DCShaderManager.cpp")
#include ".\DCShaderManager.cpp"

#pragma message("Render_Unity/Unity_Shader.cpp(20) : [4 / 4] ./DCSimpleCreatureShader.cpp")
#include ".\DCSimpleCreatureShader.cpp"

